plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

version = project.version
group = project.group

base {
	archivesName = 'voiceinject'
}

repositories {
	mavenCentral()
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
	implementation "org.slf4j:slf4j-api:2.0.16"
	include(implementation("com.alphacephei:vosk:0.3.45"))
	include(implementation("net.java.dev.jna:jna:5.17.0"))
}

tasks.register('syncIdeLibs', Copy) {
	from configurations.compileClasspath
	include 'vosk-*.jar', 'jna-5*.jar', 'gson-*.jar', 'slf4j-api-*.jar', 'fabric-*.jar'
	exclude 'jna-platform-*.jar'
	into 'lib'
	duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

tasks.named('compileJava') {
	dependsOn 'syncIdeLibs'
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}
	repositories {
	}
}
